apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
rules:
- apiGroups:
  - composition.krateo.io
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - core.krateo.io
  resources:
  - '*'
  verbs:
  - list
# For checking user permissions on resources
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - users
  - groups
  verbs:
  - impersonate