apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bff.fullname" . }}
  labels:
    {{- include "bff.labels" . | nindent 4 }}
data:
  BFF_PORT: "{{ .Values.service.port }}"
  AUTHN_STORE_NAMESPACE: {{ .Release.Namespace }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}